- name: Add a new Folder
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables_activate.txt
  tasks:

    - name: Add Folder
      arubaactivate_config:
        credential_0: "{{ activate_username }}"
        credential_1: "{{ activate_password }}"
        method: "{{ api_method }}"
        api_name: "folder"
        api_action: "update"
        data: 'json={ "folders": [ { "parentId": "4d4b127e-a7ab-4d89-9e07-508c3b529975", "folderName": "New_Test_folder"}]}'
