- name: Dump inventory
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables_activate.txt
  tasks:
    - name: Dump the contents of an inventory into a newly created CSV file
      arubaactivate_config:
        credential_0: "{{ activate_username }}"
        credential_1: "{{ activate_password }}"
        method: "{{ api_method }}"
        api_name: "inventory"
        api_action: "query"
        data: 'json={"folders": "4d4b127e-a7ab-4d89-9e07-508c3b529975"}'
      register: my_inventory

    - name: Copy contents to file
      copy :
         content : "{{ my_inventory }}"
         dest : my_log_file.csv
