- name: Add a new Rule
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables_activate.txt
  tasks:
    - name: Add Switch to AMP config Rule
      arubaactivate_config:
        credential_0: "{{ activate_username }}"
        credential_1: "{{ activate_password }}"
        method: "{{ api_method }}"
        api_name: "rule"
        api_action: "update"
        data: 'json={ "rules": [ { "ruleName": "switch_to_amp_rule", "parentFolderId": "4d4b127e-a7ab-4d89-9e07-508c3b529975", "ruleType": "provision", "provisionType": "switch_to_amp", "ampIp": "10.127.16.30", "ampGroup": "TestGroup", "ampFolder":"TestFolder", "ampSharedSecret": "Aruba@123" }]}'
