- name: Create an ACL
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a session acl with IPv4 Policies
      arubaos_controller_config:
        host: <mm-ip>
        username: <mm-username>
        password: <mm-password>
        method: POST
        config_path: <config_path>
        api_name: acl_sess
        data: { "accname": "test_acl", "acl_sess__v4policy": { "src": "shost", "dst": "dhost", "svc": "service-name", "action": "deny_opt", "service-name": "svc-icmp", "sipaddr": "1.1.1.1", "dipaddr": "2.2.2.2", "service_app": "service", "deny": true  }}
