- name: Whitelist APs
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Add AP whitelist to the controller
      arubaos_controller_config:
        host: <mm-ip>
        username: <mm-username>
        password: <mm-password>
        method: POST
        config_path: <config_path>
        api_name: wdb_cpsec_add_mac
        data: { "ap_name": "test_ap", "ap_group": "default", "name": "<ap-mac>" }
