- name: Create and configure a server group profile
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a server group and a radius server to it
      arubaos_controller_config:
        host: <mm-ip>
        username: <mm-username>
        password: <mm-password>
        method: POST
        config_path: <config_path>
        api_name: server_group_prof
        data: { "sg_name":"test", "auth_server": {"name": "test_radius_server"} }
