- name: Sample playbook to execute a show command and get all the configuration of a node
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.txt
  tasks:
    - name: Execute a show version command
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "GET"
        config_path: "{{ configuration_path }}"
        api_name: showcommand
        data: { "command": "show version" }

    - name: Get all the configuration of a node
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "GET"
        config_path: "{{ configuration_path }}"
        api_name: config
