- name: Add a new Endpoint
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables_clearpass.txt

  tasks:
    - name: Add an Endpoint
      arubaclearpass_config:
        host: "{{ clearpass_ip }}"
        client_id: "{{ clearpass_client_id }}"
        client_secret: "{{ clearpass_client_secret }}"
        method: "{{ clearpass_method }}"
        api_name: endpoint
        data: {"mac_address": "11:22:33:44:55:66", "status": "Unknown"}
