- name: Obtain an access token for CPPM
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables_clearpass.txt

  tasks:
    - name: Add a Role
      arubaclearpass_config:
        host: "{{ clearpass_ip }}"
        client_id: "{{ clearpass_client_id }}"
        client_secret: "{{ clearpass_client_secret }}"
        api_name: local-user
        method: "{{ clearpass_method }}"
        data: { "user_id": "new_user", "password": "admin123", "username": "New User", "role_name": "[Employee]" }
